apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v2
  namespace: canary-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v2
  template:
    metadata:
      labels:
        app: payment
        version: v2
    spec:
      containers:
        - name: payment
          image: hashicorp/http-echo:1.0
          args:
            - "-text=payment service version 2"
          ports:
            - containerPort: 5678
