apiVersion: apps/v1
kind: Deployment
metadata:
  name: labor-v2
  namespace: canary-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labor
      version: v2
  template:
    metadata:
      labels:
        app: labor
        version: v2
    spec:
      containers:
        - name: labor
          image: hashicorp/http-echo:1.0
          args:
            - "-text=labor service version 2"
          ports:
            - containerPort: 5678
