apiVersion: apps/v1
kind: Deployment
metadata:
  name: labor-v1
  namespace: canary-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labor
      version: v1
  template:
    metadata:
      labels:
        app: labor
        version: v1
    spec:
      containers:
        - name: labor
          image: hashicorp/http-echo:1.2
          args:
            - "-text=labor service version 1"
          ports:
            - containerPort: 5678
